#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_INPUT_FPC1020)		+= fpc1020_tee.o
obj-$(CONFIG_FINGERPRINT_GOODIX_GF318M) += goodix/
obj-$(CONFIG_HALL)		+= hall.o
